# Generated by Django 5.2.5 on 2026-02-11 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("onboarding_type", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
                (
                    "legal_id_front",
                    models.ImageField(
                        blank=True, null=True, upload_to="legal_id_fronts"
                    ),
                ),
                (
                    "legal_id_back",
                    models.ImageField(
                        blank=True, null=True, upload_to="legal_id_backs"
                    ),
                ),
            ],
        ),
    ]
