# Generated by Django 5.2.5 on 2026-02-11 17:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_provider_id_alter_provider_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="legal_id_back",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.provider_image_path
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="legal_id_front",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.provider_image_path
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.provider_image_path
            ),
        ),
    ]
