# Generated by Django 5.2.5 on 2026-02-11 18:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_provider_name_remove_provider_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provider",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.customer_image_path
            ),
        ),
    ]
