# Generated by Django 5.2.5 on 2026-02-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_customer_name_provider_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="provider",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="provider",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="provider",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
