# Generated by Django 5.2.5 on 2026-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_tag_service_servicecredential_servicemedia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecredential",
            name="file",
            field=models.FileField(upload_to="media/services/credentials/"),
        ),
        migrations.AlterField(
            model_name="servicemedia",
            name="image",
            field=models.ImageField(upload_to="media/services/media/"),
        ),
    ]
